# Generated by Django 3.2.7 on 2021-11-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price_discount',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
