# Generated by Django 3.2.7 on 2021-11-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_rename_is_accept_finalorder_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
