# Generated by Django 3.2.7 on 2021-11-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0006_finalorder_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='notes',
            field=models.TextField(),
        ),
    ]
