# Generated by Django 3.2.7 on 2021-11-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0008_auto_20211110_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='address',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='city',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='post_code',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
