# Generated by Django 3.2.7 on 2021-11-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0009_auto_20211110_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=20000, null=True),
        ),
    ]
