# Generated by Django 3.2.7 on 2021-11-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0035_productreview_answer'),
        ('order_app', '0011_alter_finalorder_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.product'),
        ),
    ]
