# Generated by Django 3.2.7 on 2021-11-10 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0012_alter_finalorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.orders'),
        ),
    ]
