# Generated by Django 3.2.7 on 2021-11-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0014_auto_20211110_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='first_name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='last_name',
            field=models.CharField(max_length=2000),
        ),
    ]
