# Generated by Django 3.2.7 on 2021-11-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0015_auto_20211110_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='product',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
