# Generated by Django 3.2.7 on 2021-11-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0016_finalorder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='product',
            field=models.CharField(max_length=2000),
        ),
    ]
