# Generated by Django 3.2.7 on 2021-11-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0017_alter_finalorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
