# Generated by Django 3.2.7 on 2021-11-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0018_finalorder_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalorder',
            name='description',
        ),
    ]
