# Generated by Django 3.2.7 on 2021-11-15 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0037_auto_20211115_1755'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_app', '0019_remove_finalorder_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalorder',
            options={'verbose_name': 'سبد خرید نهایی (آماده ارسال)', 'verbose_name_plural': 'سبد های خرید نهایی (آماده ارسال)'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد های خرید'},
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='address',
            field=models.CharField(max_length=20000, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='city',
            field=models.CharField(max_length=2000, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='count',
            field=models.IntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='first_name',
            field=models.CharField(max_length=2000, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='ارسال، شده / نشده'),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='last_name',
            field=models.CharField(max_length=2000, verbose_name='نام خانوداگی'),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='notes',
            field=models.CharField(blank=True, max_length=20000, null=True, verbose_name='نوشته ها'),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.orders', verbose_name='سبد خرید'),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='post_code',
            field=models.CharField(max_length=11, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='product',
            field=models.CharField(max_length=2000, verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='color',
            field=models.CharField(max_length=2000, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='count',
            field=models.IntegerField(default=None, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_created',
            field=models.DateTimeField(null=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='پرداخت، شده / نشده'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.IntegerField(default=None, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price_discount',
            field=models.IntegerField(default=None, null=True, verbose_name='قیمت تخفیف خورده'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='size',
            field=models.CharField(max_length=2000, verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
