# Generated by Django 3.2.7 on 2021-10-08 15:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
