# Generated by Django 3.2.7 on 2021-10-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field=438, upload_to='images', width_field=438),
        ),
    ]
