# Generated by Django 3.2.7 on 2021-10-09 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_brand',
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.ManyToManyField(blank=True, to='shop_app.brand'),
        ),
    ]
