# Generated by Django 3.2.7 on 2021-10-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_auto_20211009_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_brand',
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.ManyToManyField(blank=True, to='shop_app.Brand'),
        ),
    ]
