# Generated by Django 3.2.7 on 2021-10-11 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_auto_20211011_1846'),
        ('shop_app', '0009_auto_20211011_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryclass',
            name='category_mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cateories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.categoryclass'),
        ),
    ]
