# Generated by Django 3.2.7 on 2021-10-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_auto_20211011_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cateories',
            new_name='categories',
        ),
    ]
