# Generated by Django 3.2.7 on 2021-10-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0014_auto_20211014_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='images', verbose_name='Image (1000 * 1000)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_title',
            field=models.CharField(blank=True, default=None, max_length=2000),
        ),
    ]
