# Generated by Django 3.2.7 on 2021-10-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0015_auto_20211014_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='images', verbose_name='Image (1000 * 1000)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_title',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
