# Generated by Django 3.2.7 on 2021-10-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0016_auto_20211014_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_title',
        ),
    ]
