# Generated by Django 3.2.7 on 2021-10-17 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0018_auto_20211014_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0, help_text='0-100 rang')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_discount',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop_app.offer'),
            preserve_default=False,
        ),
    ]
