# Generated by Django 3.2.7 on 2021-10-17 15:06

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0019_auto_20211017_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount',
            field=models.IntegerField(blank=True, default=0, help_text='0-100 rang'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.categoryclass'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images', verbose_name='Image (1000 * 1000)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_discount',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.offer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
