# Generated by Django 3.2.7 on 2021-10-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0022_auto_20211017_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_discount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
