# Generated by Django 3.2.7 on 2021-10-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0023_alter_product_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount',
            field=models.FloatField(blank=True, default=None, help_text='0-100 rang', null=True),
        ),
    ]
