# Generated by Django 3.2.7 on 2021-10-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0025_alter_offer_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.AddField(
            model_name='product',
            name='product_final_price',
            field=models.IntegerField(blank=True, default=None, editable=False, null=True),
        ),
    ]
