# Generated by Django 3.2.7 on 2021-10-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0026_auto_20211017_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_final_price',
        ),
    ]
