# Generated by Django 3.2.7 on 2021-10-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0027_remove_product_product_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_discount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
