# Generated by Django 3.2.7 on 2021-10-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0030_product_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name_in_url',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
