# Generated by Django 3.2.7 on 2021-10-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0031_product_product_name_in_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name_in_url',
            field=models.SlugField(blank=True, help_text='product slug name', max_length=200, null=True),
        ),
    ]
