# Generated by Django 3.2.7 on 2021-10-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0032_alter_product_product_name_in_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_published'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
