# Generated by Django 3.2.7 on 2021-10-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0033_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name': 'Product Review', 'verbose_name_plural': 'Product Reviews'},
        ),
    ]
