# Generated by Django 3.2.7 on 2021-10-28 18:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0034_alter_productreview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='answer',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
