# Generated by Django 3.2.7 on 2021-11-12 10:26

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewProductBottomBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, help_text='alt text', max_length=200)),
                ('url', models.URLField(default=None, help_text='https://....')),
                ('image', models.ImageField(help_text='575 x 200', upload_to='banners/NewProductBottomBanner/')),
            ],
        ),
        migrations.CreateModel(
            name='OfferSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', tinymce.models.HTMLField(default=None)),
                ('url', models.URLField(default=None, help_text='https://....')),
                ('image', models.ImageField(help_text='1110 x 345', upload_to='banners/OfferSlide/')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, help_text='alt text', max_length=200)),
                ('sub_title', models.CharField(default=None, help_text='alt text', max_length=200)),
                ('image', models.ImageField(help_text='67 x 57', upload_to='banners/ShoppingArea/')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, help_text='just show in admin panel', max_length=200)),
                ('description', tinymce.models.HTMLField(default=None)),
                ('url', models.URLField(help_text='https://....')),
                ('image', models.ImageField(help_text='1110px x 520px', upload_to='slider/')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
        migrations.CreateModel(
            name='SliderBottomBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, help_text='alt text', max_length=200)),
                ('url', models.URLField(default=None, help_text='https://....')),
                ('image', models.ImageField(help_text='722 x 251', upload_to='banners/SliderBottomBanner/')),
            ],
        ),
        migrations.CreateModel(
            name='SliderLeftBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, help_text='alt text', max_length=200)),
                ('url', models.URLField(default=None, help_text='https://....')),
                ('image', models.ImageField(help_text='310 x 520', upload_to='banners/SliderLeftBanner/')),
            ],
        ),
        migrations.CreateModel(
            name='TrendingProductsUpBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, help_text='alt text', max_length=200)),
                ('url', models.URLField(default=None, help_text='https://....')),
                ('image', models.ImageField(help_text='575 x 200', upload_to='banners/TrendingProductsUpBanner/')),
            ],
        ),
    ]
