# Generated by Django 3.2.7 on 2021-11-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingarea',
            name='image',
        ),
    ]
