# Generated by Django 3.2.7 on 2021-11-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_app', '0003_shoppingarea_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingarea',
            name='image',
            field=models.ImageField(help_text='67 x 57', upload_to='banners/ShoppingArea/'),
        ),
    ]
