# Generated by Django 3.2.7 on 2021-11-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider_app', '0008_auto_20211112_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewProductBottomBanner',
        ),
        migrations.DeleteModel(
            name='TrendingProductsUpBanner',
        ),
    ]
