# Generated by Django 3.2.7 on 2021-11-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_app', '0010_productlistbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlistbanner',
            name='url',
            field=models.URLField(default=None, help_text='https://....'),
        ),
    ]
