# Generated by Django 3.2.7 on 2021-11-15 14:25

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_app', '0011_productlistbanner_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerslide',
            options={'verbose_name': 'اسلاید تخفیف ویژه', 'verbose_name_plural': 'اسلاید های تخفیف ویژه'},
        ),
        migrations.AlterModelOptions(
            name='productlistbanner',
            options={'verbose_name': 'بنر صفحه ی لیست محصولات', 'verbose_name_plural': 'بنر های صفحه ی لیست محصولات'},
        ),
        migrations.AlterModelOptions(
            name='shoppingarea',
            options={'verbose_name': 'ویژگی سایت برای خریداران', 'verbose_name_plural': 'ویژگی های سایت برای خریداران'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدر ها'},
        ),
        migrations.AlterModelOptions(
            name='sliderbottombanner',
            options={'verbose_name': 'بنر پایین اسلایدر', 'verbose_name_plural': 'بنر های پایین اسلایدر'},
        ),
        migrations.AlterModelOptions(
            name='sliderleftbanner',
            options={'verbose_name': 'بنر سمت چپ اسلایدر', 'verbose_name_plural': 'بنر های سمت چپ اسلایدر'},
        ),
        migrations.AlterField(
            model_name='offerslide',
            name='image',
            field=models.ImageField(help_text='1110 x 345', upload_to='banner/OfferSlide/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='offerslide',
            name='title',
            field=tinymce.models.HTMLField(default=None, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='offerslide',
            name='url',
            field=models.URLField(default=None, help_text='https://....', verbose_name='آدرس اینترنتی'),
        ),
        migrations.AlterField(
            model_name='productlistbanner',
            name='image',
            field=models.ImageField(help_text='310 x 520', upload_to='banner/ProductListBanner/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='productlistbanner',
            name='title',
            field=models.CharField(default=None, help_text='alt text', max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='productlistbanner',
            name='url',
            field=models.URLField(default=None, help_text='https://....', verbose_name='آدرس اینترنتی'),
        ),
        migrations.AlterField(
            model_name='shoppingarea',
            name='image',
            field=models.ImageField(help_text='67 x 57', upload_to='banner/ShoppingArea/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='shoppingarea',
            name='sub_title',
            field=models.CharField(default=None, help_text='alt text', max_length=200, verbose_name='زیر عنوان'),
        ),
        migrations.AlterField(
            model_name='shoppingarea',
            name='title',
            field=models.CharField(default=None, help_text='alt text', max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=tinymce.models.HTMLField(default=None, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(help_text='1110px x 520px', upload_to='slider/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(default=None, help_text='just show in admin panel', max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.URLField(help_text='https://....', verbose_name='آدرس اینترنتی'),
        ),
        migrations.AlterField(
            model_name='sliderbottombanner',
            name='image',
            field=models.ImageField(help_text='722 x 251', upload_to='banner/SliderBottomBanner/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='sliderbottombanner',
            name='title',
            field=models.CharField(default=None, help_text='alt text', max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='sliderbottombanner',
            name='url',
            field=models.URLField(default=None, help_text='https://....', verbose_name='آدرس اینترنتی'),
        ),
        migrations.AlterField(
            model_name='sliderleftbanner',
            name='image',
            field=models.ImageField(help_text='310 x 520', upload_to='banner/SliderLeftBanner/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='sliderleftbanner',
            name='title',
            field=models.CharField(default=None, help_text='alt text', max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='sliderleftbanner',
            name='url',
            field=models.URLField(default=None, help_text='https://....', verbose_name='آدرس اینترنتی'),
        ),
    ]
