# Generated by Django 3.2.7 on 2021-10-22 16:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='the blog article title', max_length=200, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, help_text='the article content', null=True)),
                ('image', models.ImageField(blank=True, help_text='the article image', null=True, upload_to='blog/images/')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2021, 10, 22, 19, 51, 50, 527797))),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('visit_count', models.IntegerField(default=0, editable=False)),
                ('is_published', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='article tag', max_length=200)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('website', models.CharField(blank=True, max_length=2000, null=True)),
                ('text', models.TextField()),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('is_accept', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.blog')),
            ],
            options={
                'verbose_name': 'Blog Comment',
                'verbose_name_plural': 'Blog Comments',
            },
        ),
    ]
