# Generated by Django 3.2.7 on 2021-10-22 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_alt',
            field=models.CharField(blank=True, help_text='image content for alt in SEO', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 20, 9, 16, 424828)),
        ),
    ]
