# Generated by Django 3.2.7 on 2021-10-22 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20211022_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_in_url',
            field=models.SlugField(blank=True, help_text='the blog article url title', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 34, 8, 28875)),
        ),
    ]
