# Generated by Django 3.2.7 on 2021-10-23 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20211023_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 21, 53, 53, 164932)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, help_text='the article image (825 * 580)', null=True, upload_to='blog/images/'),
        ),
    ]
