# Generated by Django 3.2.7 on 2021-10-23 18:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_alter_blog_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog_app.categorychild'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(default=None, help_text='the article content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 22, 15, 53, 960890)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=None, help_text='the article image (825 * 580)', upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_alt',
            field=models.CharField(default=None, help_text='image content for alt in SEO', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default=None, help_text='the blog article title', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_in_url',
            field=models.SlugField(default=None, help_text='the blog article url title', max_length=500),
        ),
    ]
