# Generated by Django 3.2.7 on 2021-10-28 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_auto_20211026_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 15, 12, 21, 94227)),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
