# Generated by Django 3.2.7 on 2021-11-15 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0031_alter_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date_created'], 'verbose_name': 'بلاگ', 'verbose_name_plural': 'بلاگ ها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='categorychild',
            options={'verbose_name': 'دسته بندی فرزند', 'verbose_name_plural': 'دسته بندی های فرزند'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسب ها'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog_app.categorychild', verbose_name='انتخاب دسته بندی'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(default=None, help_text='the article content', verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=None, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بروز رسانی'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=None, help_text='the article image (825 * 580)', upload_to='blog/images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_alt',
            field=models.CharField(default=None, help_text='image content for alt in SEO', max_length=1000, verbose_name='توضیحات تصویر'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='منتشر، شود / نشود'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default=None, help_text='the blog article title', max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_in_url',
            field=models.SlugField(default=None, help_text='the-blog-article-url-title', max_length=500, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='visit_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='test category', max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='test-category', max_length=400, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='categorychild',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.category', verbose_name='دسته بندی مادر'),
        ),
        migrations.AlterField(
            model_name='categorychild',
            name='name',
            field=models.CharField(help_text='test category', max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='categorychild',
            name='slug',
            field=models.SlugField(help_text='test-category', max_length=400, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True, verbose_name='جواب'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.blog', verbose_name='نام بلاگ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_send',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_accept',
            field=models.BooleanField(default=False, verbose_name='قبول، شود / نشود'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='پیغام'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.blog', verbose_name='بلاگ'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='article tag', max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(verbose_name='اسلاگ'),
        ),
    ]
