# Generated by Django 3.2.7 on 2021-10-29 16:31

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField(default=None)),
                ('image', models.ImageField(help_text='image (960 * 625)', upload_to='about-us/images/')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='Successfully',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('count', models.IntegerField(default=0, help_text='successfully count')),
                ('icon_class_name', models.CharField(help_text='Enter icon class name', max_length=10100)),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutUs_app.aboutus')),
            ],
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutUs_app.aboutus')),
            ],
        ),
    ]
