# Generated by Django 3.2.7 on 2021-10-29 16:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=tinymce.models.HTMLField(default=None),
        ),
    ]
