# Generated by Django 3.2.7 on 2021-10-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs_app', '0003_aboutus_title_in_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='title_in_admin',
            field=models.CharField(max_length=1000),
        ),
    ]
