# Generated by Django 3.2.7 on 2021-11-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس های کاربران'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='عنوان پیغام'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.TextField(verbose_name='پیغام'),
        ),
    ]
