# Generated by Django 3.2.7 on 2021-10-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountUser',
        ),
    ]
