# Generated by Django 3.2.7 on 2021-10-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/user/'),
        ),
    ]
