# Generated by Django 3.2.7 on 2021-10-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_alter_myuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='../static_cdn/static_root/avatars/1.png', null=True, upload_to='images/user/'),
        ),
    ]
