# Generated by Django 3.2.7 on 2021-11-04 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0009_alter_myuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='myuser',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.IntegerField(default=None, validators=[django.core.validators.MaxLengthValidator(limit_value=11, message='11 numbers'), django.core.validators.MinLengthValidator(limit_value=11, message='11 numbers')]),
        ),
        migrations.AddField(
            model_name='myuser',
            name='post_code',
            field=models.IntegerField(default=None, validators=[django.core.validators.MaxLengthValidator(limit_value=15, message='15 numbers'), django.core.validators.MinLengthValidator(limit_value=15, message='15 numbers')]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='avatars/4.png', null=True, upload_to='images/user/'),
        ),
    ]
