# Generated by Django 3.2.7 on 2021-11-04 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0019_auto_20211104_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.IntegerField(default=None, validators=[django.core.validators.MaxLengthValidator(limit_value=11, message='11 numbers'), django.core.validators.MinLengthValidator(limit_value=11, message='11 numbers')]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='post_code',
            field=models.IntegerField(default=None, validators=[django.core.validators.MaxLengthValidator(limit_value=15, message='15 numbers'), django.core.validators.MinLengthValidator(limit_value=15, message='15 numbers')]),
        ),
    ]
