# Generated by Django 3.2.7 on 2021-11-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0023_auto_20211104_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='post_code',
            field=models.IntegerField(default=None),
        ),
    ]
