# Generated by Django 3.2.7 on 2021-11-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0025_auto_20211104_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
