# Generated by Django 3.2.7 on 2021-11-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0026_auto_20211104_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='post_code',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='avatars/1.png', null=True, upload_to='images/user/'),
        ),
    ]
