# Generated by Django 3.2.7 on 2021-11-05 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0032_alter_myuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='post_code',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MinLengthValidator(limit_value=10, message='')]),
        ),
    ]
