# Generated by Django 3.2.7 on 2021-11-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0065_alter_myuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
