# Generated by Django 3.2.7 on 2021-10-25 19:05

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('home_title', models.CharField(max_length=1000000)),
                ('logo', models.ImageField(help_text='site logo', upload_to='logos/', verbose_name='Logo (121 * 37)')),
                ('address', models.CharField(max_length=1000)),
                ('telephone', models.CharField(help_text='Telephone Number', max_length=30)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('about_we', tinymce.models.HTMLField(help_text='about we')),
                ('copyright', tinymce.models.HTMLField(max_length=200)),
                ('subscribe_text', tinymce.models.HTMLField(max_length=500)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SocialName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='for example: instagram', max_length=200)),
            ],
            options={
                'verbose_name': 'Social Name',
                'verbose_name_plural': 'Social Names',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='for example: https://instagram.com/username')),
                ('network', models.ForeignKey(help_text='Selected', on_delete=django.db.models.deletion.CASCADE, to='settings_app.socialname')),
            ],
            options={
                'verbose_name': 'Social Network',
                'verbose_name_plural': 'Social Networks',
                'ordering': ['-id'],
            },
        ),
    ]
