# Generated by Django 3.2.7 on 2021-10-28 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_footerlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, help_text='https://.....', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='payment_image/', verbose_name='payment image (287 * 23)')),
                ('settings', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='settings_app.sitesettings')),
            ],
        ),
    ]
