# Generated by Django 3.2.7 on 2021-10-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='image',
            field=models.ImageField(default=None, upload_to='payment_image/', verbose_name='payment image (287 * 23)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='url',
            field=models.URLField(default=None, help_text='https://.....'),
        ),
    ]
