# Generated by Django 3.2.7 on 2021-10-29 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0006_auto_20211028_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='email',
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, help_text='Email', max_length=254)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_app.sitesettings')),
            ],
        ),
    ]
