# Generated by Django 3.2.7 on 2021-10-29 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0007_auto_20211029_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='telephone',
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(default=None, help_text='Telephone Number', max_length=30)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_app.sitesettings')),
            ],
        ),
    ]
