# Generated by Django 3.2.7 on 2021-11-15 14:25

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0008_auto_20211029_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emails',
            options={'verbose_name': 'ایمیل', 'verbose_name_plural': 'ایمیل ها'},
        ),
        migrations.AlterModelOptions(
            name='footerlinks',
            options={'verbose_name': 'آدرس بخش زیرین سایت', 'verbose_name_plural': 'آدرس های یخش زیرین سایت'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'شرکت واسط پرداخت اینترنتی', 'verbose_name_plural': 'شرکت های واسط پرداخت اینترنتی'},
        ),
        migrations.AlterModelOptions(
            name='phones',
            options={'verbose_name': 'تلفن', 'verbose_name_plural': 'تلفن ها'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'ordering': ['-id'], 'verbose_name': 'تنظیم سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
        migrations.AlterModelOptions(
            name='socialname',
            options={'ordering': ['-id'], 'verbose_name': 'نام شبکه ی اجتماعی', 'verbose_name_plural': ' نام های شبکه های اجتماعی'},
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'ordering': ['-id'], 'verbose_name': 'شبکه اجتماعی', 'verbose_name_plural': 'شبکه های اجتماعی'},
        ),
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.EmailField(default=None, help_text='Email', max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='footerlinks',
            name='name',
            field=models.CharField(default=None, max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='footerlinks',
            name='url',
            field=models.URLField(default=None, help_text='https://.....', verbose_name='ادرس اینترنتی'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='image',
            field=models.ImageField(default=None, upload_to='payment_image/', verbose_name='تصویر (287 * 23)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(default=None, max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='url',
            field=models.URLField(default=None, help_text='https://.....', verbose_name='آدرس اینترنتی'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='telephone',
            field=models.CharField(default=None, help_text='Telephone Number', max_length=30, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_we',
            field=tinymce.models.HTMLField(help_text='about we', verbose_name='درباره ما'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(max_length=1000, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright',
            field=tinymce.models.HTMLField(max_length=200, verbose_name='قانون کپی رایت'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_title',
            field=models.CharField(max_length=1000000, verbose_name='عنوان صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(help_text='site logo', upload_to='logos/', verbose_name='لوگو (121 * 37)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(max_length=200, verbose_name='عنوان سایت'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='subscribe_text',
            field=tinymce.models.HTMLField(max_length=500, verbose_name='عنوان دنبال کردن ما'),
        ),
        migrations.AlterField(
            model_name='socialname',
            name='name',
            field=models.CharField(help_text='for example: instagram', max_length=200, verbose_name='نام شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='network',
            field=models.ForeignKey(help_text='Selected', on_delete=django.db.models.deletion.CASCADE, to='settings_app.socialname', verbose_name='شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='url',
            field=models.URLField(help_text='for example: https://instagram.com/username', verbose_name='آدرس اینترنتی'),
        ),
    ]
