# Generated by Django 3.2.7 on 2021-11-15 14:25

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'سوال متداول', 'verbose_name_plural': 'سوالات متداول'},
        ),
        migrations.AlterModelOptions(
            name='frequentlyaccordion',
            options={'verbose_name': 'سوال متداول', 'verbose_name_plural': 'سوالات متداول'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='توضیحات کلی'),
        ),
        migrations.AlterField(
            model_name='frequentlyaccordion',
            name='faq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq_app.faq', verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='frequentlyaccordion',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='frequentlyaccordion',
            name='title',
            field=models.CharField(max_length=2000, verbose_name='عنوان'),
        ),
    ]
